### ISSUE TITLE
Can provide test files ?

### ISSUE THREAD

**Issue by xndless** [JackieHanLab/SenCID#2]
It is hoped that the author can upload test files "origin_matrix_GSE94980.txt" to guide the production of user input matrix and process localization. Thanks so much !

**Comment by merlinTFG** [comment]
you can find it in the 'demo' file

**Comment by biobirds9** [comment]
> you can find it in the 'demo' file

Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”

**Comment by merlinTFG** [comment]
> > you can find it in the 'demo' file
> 
> Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”

you should install SenCID first

**Comment by biobirds9** [comment]
> > > you can find it in the 'demo' file
> > 
> > 
> > Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”
> 
> you should install SenCID first

 I've installed the package and I'm still getting this problem. Do you have any idea what's causing it?

**Comment by SherryMiyano** [comment]
> > > > you can find it in the 'demo' file
> > > 
> > > 
> > > Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”
> > 
> > 
> > you should install SenCID first
> 
> I've installed the package and I'm still getting this problem. Do you have any idea what's causing it?

Hello, have you activated the corresponding conda environment? where you can check the 'pip list' to find SenCID. Another method to check whether it's correctly installed is by just typing 'SenCID --help' in your command line (not on python) to see whether the help messages pop up.

**Comment by biobirds9** [comment]
> > > > > you can find it in the 'demo' file
> > > > 
> > > > 
> > > > Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”
> > > 
> > > 
> > > you should install SenCID first
> > 
> > 
> > I've installed the package and I'm still getting this problem. Do you have any idea what's causing it?
> 
> Hello, have you activated the corresponding conda environment? where you can check the 'pip list' to find SenCID. Another method to check whether it's correctly installed is by just typing 'SenCID --help' in your command line (not on python) to see whether the help messages pop up.

Hello, I have successfully installed SenCID and activated the environment, but I am still experiencing this problem. May I ask if you have a solution for this?
![AC`IC9W3@X9O50JUBYG%PTV](https://github.com/JackieHanLab/SenCID/assets/99642940/98634321-5c99-4d03-b0d6-94546effae43)
![EO0ZS@1@C2%E5W}XJ58X1`Y](https://github.com/JackieHanLab/SenCID/assets/99642940/75ea6f4c-5fcf-4168-b912-c87e27058d32)
![)WO5$PA(7QX~U)ZP4CTPF@U](https://github.com/JackieHanLab/SenCID/assets/99642940/f00cc251-8e64-4bcc-99da-3965bca6dfeb)

**Comment by SherryMiyano** [comment]
> > > > > > you can find it in the 'demo' file
> > > > > 
> > > > > 
> > > > > Hello, are you experiencing this error?“ModuleNotFoundError: No module named 'SenCID.api'; 'SenCID' is not a package”
> > > > 
> > > > 
> > > > you should install SenCID first
> > > 
> > > 
> > > I've installed the package and I'm still getting this problem. Do you have any idea what's causing it?
> > 
> > 
> > Hello, have you activated the corresponding conda environment? where you can check the 'pip list' to find SenCID. Another method to check whether it's correctly installed is by just typing 'SenCID --help' in your command line (not on python) to see whether the help messages pop up.
> 
> Hello, I have successfully installed SenCID and activated the environment, but I am still experiencing this problem. May I ask if you have a solution for this? ![ACIC9W3@X9O50JUBYG%PTV](https://github.com/JackieHanLab/SenCID/assets/99642940/98634321-5c99-4d03-b0d6-94546effae43) ![EO0ZS@1@C2%E5W}XJ58X1Y](https://private-user-images.githubusercontent.com/99642940/323972173-75ea6f4c-5fcf-4168-b912-c87e27058d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzQxNDgsIm5iZiI6MTcxMzUzMzg0OCwicGF0aCI6Ii85OTY0Mjk0MC8zMjM5NzIxNzMtNzVlYTZmNGMtNWZjZi00MTY4LWI5MTItYzg3ZTI3MDU4ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzMzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZTNjMDhiMDQ0NDFkZjZiOGQ2Y2I4NWQ4ZTdlMTljY2RiNDdiZjBmZmU2MTAxY2UzNzViOTcxNTMxOGY2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9EB5zk6xJAtbOrIg4sL0TSYdFLXEXufMkFr1kQvFdU) ![)WO5$PA(7QX~U)ZP4CTPF@U](https://private-user-images.githubusercontent.com/99642940/323972226-f00cc251-8e64-4bcc-99da-3965bca6dfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzQxNDgsIm5iZiI6MTcxMzUzMzg0OCwicGF0aCI6Ii85OTY0Mjk0MC8zMjM5NzIyMjYtZjAwY2MyNTEtOGU2NC00YmNjLTk5ZGEtMzk2NWJjYTZkZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzMzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OWY0NDIwOTc5ZWQ0MGFkNDJjZTBhNDhhNWUwY2VkNjYzNzc2ZmFkMzU2NDkxZTk3MzhkMTk3MzIwMzM3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRLfzhANuMbNnbiMLqcgHXMg7D7RJczckDVE7QoLaHs)

It seems that you are using python and the command line in different interface... Please make sure your python interface (spyder, jupyter, etc) are working in the activated environment, and your current working directory do not contain any file or fold that use the exact same name "SenCID".

**Comment by grimwoo** [comment]
@SherryMiyano 
Hi, after installation of SenCID(```Successfully installed SenCID-1.0.0 cachetools-4.2.4 google-auth-1.35.0 scipy-1.4.1 tensorboard-2.2.2 tensorflow-estimator-2.2.0```), the ```SenCID --help``` resulted in error:
```
Traceback (most recent call last):
  File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/bin/SenCID", line 5, in <module>
    from SenCID.__main__ import main
  File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/SenCID/__main__.py", line 11, in <module>
    from absl import app
  File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/app.py", line 37, in <module>
    from absl import flags
  File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
Could you please help me?

**Comment by SherryMiyano** [comment]
> @SherryMiyano Hi, after installation of SenCID(`Successfully installed SenCID-1.0.0 cachetools-4.2.4 google-auth-1.35.0 scipy-1.4.1 tensorboard-2.2.2 tensorflow-estimator-2.2.0`), the `SenCID --help` resulted in error:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/bin/SenCID", line 5, in <module>
>     from SenCID.__main__ import main
>   File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/SenCID/__main__.py", line 11, in <module>
>     from absl import app
>   File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/app.py", line 37, in <module>
>     from absl import flags
>   File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
>     from absl.flags import _argument_parser
>   File "/mnt/d/Software/WinUbuntu/Anaconda/Install/envs/SenCID/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
>     class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
> ```
> 
> Could you please help me?

Hello, I've seen your comments under other issues~ Thanks for using SenCID! I think the origin of the 'metaclass' error is that your environment already exists some other packages before installing SenCID, and there might be some conflicts. 

If that's a case, I would strongly recommend the creation of a new conda environment and install SenCID directly according to the [ReadMe](https://github.com/JackieHanLab/SenCID/blob/main/README.md), or simpler, clone the environment from [SenCID.yaml](https://github.com/JackieHanLab/SenCID/blob/main/SenCID.yaml). 

Please let me know if there are further problems.

**Comment by grimwoo** [comment]
@SherryMiyano Thank you for your quick reply. I tried the installation via ```pip install . ``` or ```conda env create -f SenCID.yaml```. However, I will try again.

**Comment by SherryMiyano** [comment]
> @SherryMiyano Thank you for your quick reply. I tried the installation via `pip install . ` or `conda env create -f SenCID.yaml`. However, I will try again.

Hi, I've just come across an issue of absl-py recently [here](https://github.com/abseil/abseil-py/issues/277), could downgrading the absl-py to 1.1.0 (as in SenCID.yaml) help?

**Comment by marryhorse** [comment]
I've installed the SenCID and I'm getting this problem. Do you have any idea what's causing it?
![image](https://github.com/JackieHanLab/SenCID/assets/170314228/0bf4b920-98c1-44b1-ba98-75bb2a24c939)

**Comment by SherryMiyano** [comment]
> I've installed the SenCID and I'm getting this problem. Do you have any idea what's causing it? ![image](https://private-user-images.githubusercontent.com/170314228/332450131-0bf4b920-98c1-44b1-ba98-75bb2a24c939.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTg3MjMsIm5iZiI6MTcxNzQxODQyMywicGF0aCI6Ii8xNzAzMTQyMjgvMzMyNDUwMTMxLTBiZjRiOTIwLTk4YzEtNDRiMS1iYTk4LTc1YmIyYTI0YzkzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMjQwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzU2MDQ5MTBkMGU5NTdhZWJhMzA2MWE0N2EyNDEwZmI5OGUyMTA1NGYyMmMxZGE1NzQxNzViODhiNWUwZGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDQhgrADxx0uoZnXqrf69Wr1oY_42jE2sG8OWuPjxGA)

Could there be some problem with the network? what about downloading the package and installing it offline?
